### ISSUE TITLE
bug with tcp dns packet parse

### ISSUE THREAD

**Issue by triste24** [objective-see/DNSMonitor#2]
@objective-see test after commenting this [line](https://github.com/objective-see/DNSMonitor/blob/main/Extension/DNSProxyProvider.m#L540)
![image](https://user-images.githubusercontent.com/17865148/223384136-da4e9ca3-31fb-4bac-9206-ab96b783bb02.png)
`length -= sizeof(uint16_t);`  seems to be unnecessary.`data.length=29` and` sizeof(uint16_t)=2`,so the length of packet is 27,no need to minus 2 again.
![image](https://user-images.githubusercontent.com/17865148/223383279-c00c0a54-4d14-4c32-8e89-4b202593f011.png)
![image](https://user-images.githubusercontent.com/17865148/223383303-ef100177-6c53-4f88-a67e-b47858f10013.png)

**Comment by objective-see** [comment]
Good catch! Much appreciated 👍🏽
