### ISSUE TITLE
dns_parse_packet return null macOS12.4 intel 

### ISSUE THREAD

**Issue by 1021811501** [objective-see/DNSMonitor#5]
dns_parse_packet return null on macOS12.4 intel, But the same dns packet resolves fine on other machines.

**Comment by objective-see** [comment]
Unfortunately this is an Apple bug 😞 
They broke the the `dns_parse_packet` function, on certain (older) versions of macOS/iOS

See the following post on Apple's developer forums: ["dns_parse_packet API not working"](https://developer.apple.com/forums/thread/706738)
